# Generated by Django 5.0.7 on 2024-10-04 13:50

import django.db.models.deletion
import ravi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='application_loan_type',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='dsaref_code',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='empref_code',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='franrefCode',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='application_loan_type',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='dsaref_code',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='empref_code',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='franrefCode',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='name',
        ),
        migrations.AlterField(
            model_name='applicationverification',
            name='personal_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_verification', to='ravi.personaldetail'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='co_applicant_age',
            field=models.DateField(max_length=2, validators=[ravi.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='homebasicdetail',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='pldisbursementdetails',
            name='verification',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='pldisbursement_detail', to='ravi.applicationverification'),
        ),
    ]
