# Generated by Django 5.0.7 on 2024-10-27 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0003_customerprofile_application_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeapplication',
            name='applicant_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicationhomeverification', to='ravi.customerprofile'),
        ),
    ]
