# Generated by Django 5.0.7 on 2024-10-29 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0004_alter_homeapplication_applicant_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeapplication',
            name='applicant_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicationverification', to='ravi.customerprofile'),
        ),
    ]
