# Generated by Django 5.0.7 on 2024-11-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0007_alter_applicantdocument_latest_3_yrs_itr_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebasicdetail',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalbasicdetail',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homebasicdetail',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='personalbasicdetail',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
