# Generated by Django 5.0.7 on 2024-11-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhanu', '0003_alter_edubasicdetailform_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalloan',
            name='mail_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='educationalloan',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
