# Generated by Django 5.0.7 on 2024-11-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhanu', '0004_alter_educationalloan_mail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edubasicdetailform',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edubasicdetailform',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
