# Generated by Django 5.0.7 on 2024-10-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbasicdetailform',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
