# Generated by Django 5.0.7 on 2024-11-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_busbasicdetailform_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessloan',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessloan',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
