# Generated by Django 5.0.7 on 2024-11-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_busbasicdetailform_expiry_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessloan',
            name='expiry_at',
        ),
        migrations.AlterField(
            model_name='businessloan',
            name='aadhar_card_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='businessloan',
            name='pan_card_number',
            field=models.CharField(max_length=10),
        ),
    ]
