# Generated by Django 5.0.7 on 2024-11-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_businessloan_expiry_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessloan',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
