# Generated by Django 5.0.7 on 2024-11-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganesh', '0002_alter_credbasicdetailform_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdetail',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
