# Generated by Django 5.0.7 on 2024-11-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganesh', '0003_creditdetail_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='credbasicdetailform',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credbasicdetailform',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
