# Generated by Django 5.0.7 on 2024-10-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seetha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carloan',
            name='ref_1_person_mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='ref_2_person_mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
