# Generated by Django 5.0.7 on 2024-11-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seetha', '0003_alter_clbasicdetail_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clbasicdetail',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='aadhar_card_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='carloan',
            name='pan_card_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clbasicdetail',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
